version: 2.1

orbs:
  go: "circleci/go@1.7.1"
  rust: "circleci/rust@1.6.0"

parameters:
  version:
    type: "string"
    default: "v1.14.19-jito"
  run:
    type: "boolean"
    default: false

workflows:
  picasso:
    when: << pipeline.parameters.run >>
    jobs:
      - build
      - publish:
          context: "github-context"
          requires:
            - build

jobs:
  build:
    executor:
      name: "rust/default"
      tag: "1.65.0"
    resource_class: "large"
    steps:
      - run:
          name: "Clone jito-solana source"
          command: >
            git clone -b << pipeline.parameters.version >> https://github.com/jito-foundation/jito-solana.git --recurse-submodules
            cd jito-solana
            git submodule update --init --recursive
      - restore_cache:
          keys:
            - 'cargo-{{ checksum "jito-solana/Cargo.lock" }}'
      - run:
          name: "Build jito-solana binary"
          command: |
            cd jito-solana
            CI_COMMIT=$(git rev-parse HEAD) scripts/cargo-install-all.sh --validator-only .
            mv "${HOME}/project/jito-solana/target/release/solana-validator" "${HOME}/project/jito-solana/target/release/solana-validator-<< pipeline.parameters.version >>"
      - save_cache:
          key: 'cargo-{{ checksum "jito-solana/Cargo.lock" }}'
          paths:
            - ~/.cargo
      - persist_to_workspace:
          root: "./jito-solana/target/release"
          paths:
            - solana-validator-*
  publish:
    executor:
      name: "go/default"
      tag: "1.17"
    steps:
      - checkout
      - attach_workspace:
          at: '/tmp/binaries'
      - run:
          name: "Install GHR"
          command: go get github.com/tcnksm/ghr
      - run:
          name: "Publish Github release"
          command: |
            ghr -t "${GITHUB_TOKEN}" \
              -n "<< pipeline.parameters.version >>" \
              -recreate "<< pipeline.parameters.version >>" \
              /tmp/binaries/solana-validator-<< pipeline.parameters.version >>
